### PR TITLE
4.4.1 next attempt

### PR DESCRIPTION
**Pull request by LaurenzV**
| Status | Commit message                                                                | HB                                                            |                                                                                                                                                                                                                                                                    |
| ------ | ----------------------------------------------------------------------------- | ------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| 🟡     | [indic-like] Move allocation of syllable() buffer var to shapers that use it  | [Link](https://github.com/harfbuzz/harfbuzz/commit/15543f70e) | apart from the one change in hb-ot-layout, the rest isn't relevant for us right?                                                                                                                                                                                   |
| 🟡     | [layout-cache] Cache lookahead                                                | [Link](https://github.com/harfbuzz/harfbuzz/commit/bfee6839b) | can ignore, right?                                                                                                                                                                                                                                                 |
| 🟡     | [layout] Rename apply_recurse_func to specialization of dispatch_recurse_func | [Link](https://github.com/harfbuzz/harfbuzz/commit/c13ff3952) | do we have that?                                                                                                                                                                                                                                                   |
| 🟡     | [indic-like] Remove category duplication                                      | [Link](https://github.com/harfbuzz/harfbuzz/commit/607a9fe79) | Unfortunately, it's not really possible to deduplicate like they did, because of shortcomings of ragel rust... I added comments to hint to the lack of deduplication, I hope it won't cause problems in the future, but there isn't much else we can do I think... |
| 🟡     | [ucd] Update                                                                  | [Link](https://github.com/harfbuzz/harfbuzz/commit/91d00ab72) | relevant?                                                                                                                                                                                                                                                          |
| 🟡     | [indic] Disable vowel-constraints under uniscribe-bug-compatible              | [Link](https://github.com/harfbuzz/harfbuzz/commit/8bfb3e9df) | seems like we don't have this flag?                                                                                                                                                                                                                                |
| 🟡     | [indic] Clear syllables at the end of GSUB                                    | [Link](https://github.com/harfbuzz/harfbuzz/commit/ad2ab1ddb) | Seems like we don't have the clear_syllables_function... but it does seem relevant and it's also used in two other places, do you know what the rust equivalent would look like? I'm having a hard time understanding the C++ macro...                             |
| 🟡     | [indic] Remove remnants of Sinhala                                            | [Link](https://github.com/harfbuzz/harfbuzz/commit/78c5ae397) | hb-ot-shaper contains a change in the end that is alsoa bout the "uniscribe compatibility bug"                                                                                                                                                                     |
| 🟡     | [gdef] Minor harmless use of HB_OT_LAYOUT_GLYPH_CLASS_UNCLASSIFIED            | [Link](https://github.com/harfbuzz/harfbuzz/commit/b1629b0ce) | how do I translate this? or is that a ttf-parser change?                                                                                                                                                                                                           |

### CODE REVIEW

**Comment by LaurenzV** [comment]
@RazrFalcon `arabic-fallback` commits are not relevant for us, right?

**Comment by RazrFalcon** [comment]
Yep.

**Comment by LaurenzV** [comment]
@RazrFalcon not done yet, but getting close I think. There were however a couple of things I wasn't sure about, see above, would be great if you could take a look.

**Comment by LaurenzV** [comment]
Also, another question (which is not relevant for 4.4.1 but for later): The boring expansion spec is out of scope right now, right? i.e. I can ignore commits about >64k glyphs / avar2 / VARC?

**Comment by LaurenzV** [comment]
Alright, everything up to 4.4.1 is ported. So the only thing I need help with is with the orange points mentioned above.

I tried adding a CI check with `no-default-features`, but for some reason, it doesn't work... But that line was not added in my PR, so not sure what I'm doing wrong.

**Comment by RazrFalcon** [comment]
>The boring expansion spec is out of scope right now, right? i.e. I can ignore commits about >64k glyphs / avar2 / VARC?

Yep. 

>Am I understanding correctly that I always need to pass std/libm?

It should be `--do-default-features --features=libm`.

>So the only thing I need help with is with the orange points mentioned above.

Will take a look.

**Comment by RazrFalcon** [comment]
>[indic-like] Move allocation of syllable() buffer var to shapers that use it | apart from the one change in hb-ot-layout, the rest isn't relevant for us right?

Yes, we do not use `HB_BUFFER_ALLOCATE_VAR` and friends. I still have no idea what they do in the first place. They do not affect shaping output.

>[layout-cache] Cache lookahead | can ignore, right?

I think so. We do not cache those values to begin with.

>[layout] Rename apply_recurse_func to specialization of dispatch_recurse_func | do we have that?

Probably not. Hard to say.

>[indic-like] Remove category duplication

A strange one, indeed. But I guess it doesn't affect us much.

> [ucd] Update | relevant?

We already have `SCRIPT_MATH` somehow... And we use `unicode-script` crate for low-level stuff anyway.

>[indic] Disable vowel-constraints under uniscribe-bug-compatible | seems like we don't have this flag?

Yep, out of scope.

>[indic] Clear syllables at the end of GSUB | Seems like we don't have the clear_syllables_function... but it does seem relevant and it's also used in two other places, do you know what the rust equivalent would look like? I'm having a hard time understanding the C++ macro...

Yes, we do not use `HB_BUFFER_ALLOCATE_VAR` and friends. See above.

>[indic] Remove remnants of Sinhala | Link | hb-ot-shaper contains a change in the end that is alsoa bout the "uniscribe compatibility bug"

Yes, we do not care about `uniscribe_bug_compatible`.

>[gdef] Minor harmless use of HB_OT_LAYOUT_GLYPH_CLASS_UNCLASSIFIED | how do I translate this? or is that a ttf-parser change?

This is `ttf_parser::gdef::GlyphClass` and in ttf-parser/rustybuzz `HB_OT_LAYOUT_GLYPH_CLASS_UNCLASSIFIED` would be `None`. This is how `ttf_parser::gdef::Table::glyph_class` works.

Also, that change in harfbuzz is no-op anyway, since `HB_OT_LAYOUT_GLYPH_CLASS_UNCLASSIFIED` is 0 to begin with. So it's just a magic number was replaced with a named one.
No effect to rustybuzz.

---

Hopefully that's all.

**Comment by RazrFalcon** [comment]
To clarify `HB_BUFFER_ALLOCATE_VAR` and stuff a bit, the way I initially wrote rustybuzz is by forking harfbuzz, removing everything that doesn't affects shaping results; removed all magic macros and stuff; and only then started incrementally porting C++ to Rust.

And if I remember correctly, as it was 4 years ago, I removed `HB_BUFFER_ALLOCATE_VAR` macros. Run tests. All of them were still passing. Job done. Not second thoughs.

**Comment by RazrFalcon** [comment]
Thanks again!

**Comment by LaurenzV** [comment]
@behdad Could you maybe clarify what `hb_syllabic_clear_var` does? Does it really just deallocate something or does it also change any values somehow?

**Comment by behdad** [comment]
> > The boring expansion spec is out of scope right now, right? i.e. I can ignore commits about >64k glyphs / avar2 / VARC?

avar2 is a bit different: It's shipped by Apple, and is enabled by default in HB. So I prefer if you implement it.

**Comment by behdad** [comment]
> @behdad Could you maybe clarify what `hb_syllabic_clear_var` does? Does it really just deallocate something or does it also change any values somehow?

No it doesn't. The whole buffer variable allocation is just sanity checking to make sure the same buffer variable is not used for two different things at the same time. Some of the caching query whether a certain variable is free to use. But if you are not porting the layout caching things, you can ignore the buffer allocations.

**Comment by LaurenzV** [comment]
Got it, thanks!

**Comment by LaurenzV** [comment]
Okay sorry, but I need to clarify again. Since we are not porting layout caching, should the following code snippet:

```rs
static void
override_features_indic (hb_ot_shape_planner_t *plan)
{
  plan->map.disable_feature (HB_TAG('l','i','g','a'));
  plan->map.add_gsub_pause (hb_syllabic_clear_var); // Don't need syllables anymore, use stop to free buffer var
}
```

be translated as (the way it currently is):
```rs
fn override_features(planner: &mut hb_ot_shape_planner_t) {
    planner
        .ot_map
        .disable_feature(hb_tag_t::from_bytes(b"liga"));
}
```

or should we still add the gsub pause, so something like:

```rs
fn override_features(planner: &mut hb_ot_shape_planner_t) {
    planner
        .ot_map
        .disable_feature(hb_tag_t::from_bytes(b"liga"));
   planner.ot_map.add_gsub_pause(None);
}
```

**Comment by behdad** [comment]
Add a None pause so behavior remains exactly the same as HB.

**Pull request merged**
