### PR TITLE
Backport to 5.0.0

### PR DESCRIPTION
**Pull request by LaurenzV**
| Status | Commit message                                                   | HB                                                            |                                                                                                                                                                                                                                                 |
| ------ | ---------------------------------------------------------------- | ------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🟢     | [tt-font] Apply VVAR.vOrg variation to VORG origin               | [Link](https://github.com/harfbuzz/harfbuzz/commit/d5921b379) | Implemented in ttf-parser. I manually verified that [https://github.com/harfbuzz/harfbuzz/issues/1694](https://github.com/harfbuzz/harfbuzz/issues/1694) is now resolved for us as well.                                                        |
| 🟡     | [glyf] Change side-bearing rounding                              | [Link](https://github.com/harfbuzz/harfbuzz/commit/6665881c7) | not relevant I think? since we don't support phantom points yet                                                                                                                                                                                 |
| 🟡     | Fix LookupFlag negation                                          | [Link](https://github.com/harfbuzz/harfbuzz/commit/d9ab805e6) | I believe this shoulddnt affect us?                                                                                                                                                                                                             |
| 🟡     | [use-table] Port to using packtab                                | [Link](https://github.com/harfbuzz/harfbuzz/commit/015aecfcd) | Unfortunately packtab seems to generate c++ code (and it's also been updated in the meanwhile)... so for now I've decided to switch to a manual implementation, hopegully when the port is done we can port the packTab code to work with rust. But see the discussion below. |
| 🟢     | [GPOS] Adjust mark attachment on multiple substitution some more | [Link](https://github.com/harfbuzz/harfbuzz/commit/a2f072314) |                                                                                                                                                                                                                                                 |
| 🟡     | [reorg] Move Coverage                                            | [Link](https://github.com/harfbuzz/harfbuzz/commit/c1e280ea7) | ttf-parser stuff I guess?                                                                                                                                                                                                                       |
| 🟢     | [arabic] Pause after calt only if no rclt                        | [Link](https://github.com/harfbuzz/harfbuzz/commit/d68507d06) |                                                                                                                                                                                                                                                 |
| 🟡     | [aat/morx] Implement language-specific forms                     | [Link](https://github.com/harfbuzz/harfbuzz/commit/2124ad890) | Where exactly can I find this ltag in our port?                                                                                                                                                                                                 |
| 🟡     | [aat/morx] Add test for previous commit                          | [Link](https://github.com/harfbuzz/harfbuzz/commit/a5dad5007) |                                                                                                                                                                                                                                                 |
| 🟡     | Add hb_language_matches()                                        | [Link](https://github.com/harfbuzz/harfbuzz/commit/f7f6d278b) |                                                                                                                                                                                                                                                 |
| 🟢     | [arabic] Make more features F_MANUAL_ZWJ                         | [Link](https://github.com/harfbuzz/harfbuzz/commit/c2baf2796) |                                                                                                                                                                                                                                                 |
| 🟢     | [GPOS/Cursive] Fix breaking of parent-child attachment           | [Link](https://github.com/harfbuzz/harfbuzz/commit/54e9ab4a9) |                                                                                                                                                                                                                                                 |
| 🟢     | [hebrew] Implement Jerusalem mark reordering                     | [Link](https://github.com/harfbuzz/harfbuzz/commit/c60d810d5) |                                                                                                                                                                                                                                                 |
| 🟢     | [hebrew] Comment                                                 | [Link](https://github.com/harfbuzz/harfbuzz/commit/d86130379) |                                                                                                                                                                                                                                                 |
| 🟢     | Add tests for multiple cursive positioning                       | [Link](https://github.com/harfbuzz/harfbuzz/commit/42f1d7794) |                                                                                                                                                                                                                                                 |
| 🟢     | [hebrew] Break out of reordering loop when pattern found         | [Link](https://github.com/harfbuzz/harfbuzz/commit/5998cd00c) |                                                                                                                                                                                                                                                 |
| 🟢     | [GPOS/CursivePos] Fix unsafe-to-break marking                    | [Link](https://github.com/harfbuzz/harfbuzz/commit/3c137ef04) |                                                                                                                                                                                                                                                 |
| 🟡     | [layout] Reduce number of closure rounds                         | [Link](https://github.com/harfbuzz/harfbuzz/commit/8d923363d) | we dont have this right?                                                                                                                                                                                                                        |

### CODE REVIEW

**Comment by RazrFalcon** [comment]
How the new USE table works? Have you simply ported C code to Rust? Because the new Python script produces C, right?

**Comment by LaurenzV** [comment]
Yeah exactly, they have a python package that somehow encodes the data more compactly, and it generates C code. I think we can rewrite it to produce Rust, but I noticed that they change the script again in the future so for now I think it's easier to do it by hand, it only changes a couple of times anyway.

**Comment by behdad** [comment]
Adding Rust output to packtab sounds like it should take 20min. I'd be happy to take that.

**Comment by LaurenzV** [comment]
That would be great if possible!

**Comment by LaurenzV** [comment]
@RazrFalcon Alright, so the main thing missing now is avar2. Would you prefer me to try implement it in ttf-parser as suggested by Behdad, or should I rather focus on backporting more commits for now?

**Comment by LaurenzV** [comment]
And I've added a note about the ones I was uncertain about again at the top.

**Comment by RazrFalcon** [comment]
I think we can skip `avar2` for now. We could mention it in the README, that this harfbuzz feature is not supported. 

To my understanding `avar2` is not part of the TrueType spec. It might become one, but not for now. So we can ignore it as an extreme edge case. We have other things to do in the mean time...

Of course if you're interested in implementing `avar2` - go ahead.

**Comment by LaurenzV** [comment]
I'll add it in the README.

**Comment by LaurenzV** [comment]
Okay, so apart from the orange points mentioned above that I was unsure about, the rest should be done.

**Comment by LaurenzV** [comment]
Closing in favor of #109, which contains all commits here + until 5.3.1.

**Comment by RazrFalcon** [comment]
Why not merge it as 5.0.0?

**Comment by LaurenzV** [comment]
I mean... we can if you want, but since I already ported until 5.3.1 might as well merge that, no? The commits from 5.0.0 are in there as well, but if you prefer it that way I will reopen one just for 5.0.0.

**Comment by RazrFalcon** [comment]
I guess I would prefer smaller patches in the future. Easier to review.
But yeah, I was just confused why have you merged two PRs into one.

**Comment by LaurenzV** [comment]
Okok, I'll keep that in mind for the future.

**Pull request closed without merging**
