### PR TITLE
Sync with 4.0.1

### PR DESCRIPTION
**Pull request by LaurenzV**
| Status | Commit message | HB | Comments |
| ------ | ------------------------------------------------------------------------- | ------------------------------------------------------------- | -------- |
| ⚪️ | [ci] Downgrade pip on MSVC jobs | [Link](https://github.com/harfbuzz/harfbuzz/commit/c4cf5ddb2) | |
| 🟢 | [arabic] Update to AMTRA revision 6 | [Link](https://github.com/harfbuzz/harfbuzz/commit/76cd8a473) | |
| 🟢 | [ot-tag] Add HB_SCRIPT_MATH (Zmth) and map it to OT ‚Äòmath‚Äô tag | [Link](https://github.com/harfbuzz/harfbuzz/commit/1bc4bad7a) | |
| ⚪️ | Revert "[ci] Downgrade pip on MSVC jobs" | [Link](https://github.com/harfbuzz/harfbuzz/commit/02a737e53) | |
| ⚪️ | [ot-math] Add hb_ot_math_get_glyph_kernings | [Link](https://github.com/harfbuzz/harfbuzz/commit/81754a5a9) | |
| ⚪️ | [ci] Upgrade pip on MSVC job | [Link](https://github.com/harfbuzz/harfbuzz/commit/e045dbf61) | |
| ⚪️ | hb-algs.hh: Fix build on Visual Studio 2015 | [Link](https://github.com/harfbuzz/harfbuzz/commit/52c536bb8) | |
| ⚪️ | meson.build: Only use get_variable() on icu_dep with pkgconfig | [Link](https://github.com/harfbuzz/harfbuzz/commit/3d22dae5f) | |
| ⚪️ | [machinery] Allow using lazy-loader with void\* | [Link](https://github.com/harfbuzz/harfbuzz/commit/689372387) | |
| ⚪️ | [subset] Add subset plan to public API. | [Link](https://github.com/harfbuzz/harfbuzz/commit/b65e48a78) | |
| ⚪️ | [subset] add subset plan reference | [Link](https://github.com/harfbuzz/harfbuzz/commit/ae8d373bc) | |
| ⚪️ | [subset] Change subset plan create to be or_fail. | [Link](https://github.com/harfbuzz/harfbuzz/commit/670ef070b) | |
| ⚪️ | [subset] Fix memory leak in plan creation. | [Link](https://github.com/harfbuzz/harfbuzz/commit/27a6c895b) | |
| ⚪️ | Add a fuzzer font | [Link](https://github.com/harfbuzz/harfbuzz/commit/af407dd24) | |
| ⚪️ | [hmtx] Remove one subset-specific method from hmtx accelerator | [Link](https://github.com/harfbuzz/harfbuzz/commit/9ba520b5d) | |
| ⚪️ | [hmtx] Remove other subset-specific method from hmtx accelerator | [Link](https://github.com/harfbuzz/harfbuzz/commit/42b119edb) | |
| ⚪️ | [test/subset] Don't hash files without reason | [Link](https://github.com/harfbuzz/harfbuzz/commit/b3f8288cc) | |
| ⚪️ | Merge pull request #3398 from harfbuzz/buffer-verify | [Link](https://github.com/harfbuzz/harfbuzz/commit/b263371b0) | |
| ⚪️ | [name] Extraneous (out) annotation in return value | [Link](https://github.com/harfbuzz/harfbuzz/commit/41815a0d6) | |
| ⚪️ | 3.4.0 | [Link](https://github.com/harfbuzz/harfbuzz/commit/0a1299613) | |
| ⚪️ | Typo | [Link](https://github.com/harfbuzz/harfbuzz/commit/db04af278) | |
| ⚪️ | [ci] Add configs-ci.yml to test different configs | [Link](https://github.com/harfbuzz/harfbuzz/commit/b2f513102) | |
| ⚪️ | Fix compiler warning | [Link](https://github.com/harfbuzz/harfbuzz/commit/7af165dbf) | |
| ⚪️ | [draw] Remove EXPERIMENTAL_API tag | [Link](https://github.com/harfbuzz/harfbuzz/commit/dd7b6e2c3) | |
| ⚪️ | [font] Add em_scaleff() that returns float | [Link](https://github.com/harfbuzz/harfbuzz/commit/6c0b65a6a) | |
| ⚪️ | [font] Add em_fscalef_[xy] That take and return float | [Link](https://github.com/harfbuzz/harfbuzz/commit/d6e49b827) | |
| ⚪️ | [draw] Convert API to float instead of hb_position_t | [Link](https://github.com/harfbuzz/harfbuzz/commit/35190dc96) | |
| ⚪️ | [main] Fix compiler warnings | [Link](https://github.com/harfbuzz/harfbuzz/commit/a428c1193) | |
| ⚪️ | [draw] Replace API Since tags with REPLACEME | [Link](https://github.com/harfbuzz/harfbuzz/commit/9a1508a2b) | |
| ⚪️ | [draw] Move hb_font_draw_glyph() to hb-draw-glyph.cc | [Link](https://github.com/harfbuzz/harfbuzz/commit/ddc36df33) | |
| ⚪️ | [draw] Remove return value of hb_font_draw_glyph() | [Link](https://github.com/harfbuzz/harfbuzz/commit/e157b5034) | |
| ⚪️ | [draw] Whitespace | [Link](https://github.com/harfbuzz/harfbuzz/commit/7ac23f4e7) | |
| ⚪️ | [draw] Another Since: tag update | [Link](https://github.com/harfbuzz/harfbuzz/commit/27dfd69fc) | |
| ⚪️ | [test-draw] Fix compiler warning | [Link](https://github.com/harfbuzz/harfbuzz/commit/157caf254) | |
| ⚪️ | [draw] Enable draw tests | [Link](https://github.com/harfbuzz/harfbuzz/commit/5207ce828) | |
| ⚪️ | Remove remaining traces of HB_EXPERIMENTAL_API | [Link](https://github.com/harfbuzz/harfbuzz/commit/e0ac6c587) | |
| ⚪️ | [draw-fuzzer] Fix signatures | [Link](https://github.com/harfbuzz/harfbuzz/commit/08e109660) | |
| ⚪️ | [draw] Fix draw signatures | [Link](https://github.com/harfbuzz/harfbuzz/commit/2bed4f46f) | |
| ⚪️ | [draw] Remove unneeded roundf() calls | [Link](https://github.com/harfbuzz/harfbuzz/commit/3b915389b) | |
| ⚪️ | [draw] Rename user_data to draw_data | [Link](https://github.com/harfbuzz/harfbuzz/commit/92e6e53b3) | |
| ⚪️ | [draw] Virtualize hb_font_draw_glyph() into hb_font_get_glyph_shape() | [Link](https://github.com/harfbuzz/harfbuzz/commit/8b4f42900) | |
| ⚪️ | [draw] Add REPLACEME | [Link](https://github.com/harfbuzz/harfbuzz/commit/cdb1a1fc0) | |
| ⚪️ | [draw] Add TODO | [Link](https://github.com/harfbuzz/harfbuzz/commit/a755f93e8) | |
| ⚪️ | [test-draw] Re-enable two disabled tests | [Link](https://github.com/harfbuzz/harfbuzz/commit/5610fa1da) | |
| ⚪️ | [draw-state] Add type and use in draw-helper | [Link](https://github.com/harfbuzz/harfbuzz/commit/fc78592e6) | |
| ⚪️ | [draw] Remove check for no-op | [Link](https://github.com/harfbuzz/harfbuzz/commit/1740916ed) | |
| ⚪️ | [draw] Simplify start_path | [Link](https://github.com/harfbuzz/harfbuzz/commit/86fcd4fe9) | |
| ⚪️ | [draw] Rename internal methods | [Link](https://github.com/harfbuzz/harfbuzz/commit/ebc2a133c) | |
| ⚪️ | [test-draw] Fix compiler warning | [Link](https://github.com/harfbuzz/harfbuzz/commit/9f05362d4) | |
| ⚪️ | [draw] Add public move_to/line_to/... API that take a draw-state | [Link](https://github.com/harfbuzz/harfbuzz/commit/a9dd9f0ba) | |
| ⚪️ | [draw-state] Pass state down to callbacks | [Link](https://github.com/harfbuzz/harfbuzz/commit/f1a9a9cca) | |
| ⚪️ | [draw] Rename internal draw_helper_t to draw_session_t | [Link](https://github.com/harfbuzz/harfbuzz/commit/c681331c3) | |
| ⚪️ | [draw] Do quadratic-to-cubic conversion in nil quadratic implementation | [Link](https://github.com/harfbuzz/harfbuzz/commit/a357e5d88) | |
| ⚪️ | [util] Use hb-draw to render alternatively to cairo-ft | [Link](https://github.com/harfbuzz/harfbuzz/commit/5d2df1208) | |
| ⚪️ | [draw] Rename internal draw_session_t to hb_draw_session_t | [Link](https://github.com/harfbuzz/harfbuzz/commit/370bec938) | |
| ⚪️ | [ft/draw] Implement hb-draw for hb-ft | [Link](https://github.com/harfbuzz/harfbuzz/commit/6d5b998f2) | |
| ⚪️ | [util/draw/ft] Use hb-draw for font-funcs=ft as well | [Link](https://github.com/harfbuzz/harfbuzz/commit/542f8269c) | |
| ⚪️ | [util/draw] Render color glyphs if cairo API available | [Link](https://github.com/harfbuzz/harfbuzz/commit/cfc06c24d) | |
| ⚪️ | [draw] Minor cleanup | [Link](https://github.com/harfbuzz/harfbuzz/commit/d6b61dff9) | |
| ⚪️ | [font/draw] Fetch shape from parent font if not implemented in font | [Link](https://github.com/harfbuzz/harfbuzz/commit/2ce19f286) | |
| ⚪️ | [draw] Add more reserved items to hb_draw_state_t | [Link](https://github.com/harfbuzz/harfbuzz/commit/4f2704adb) | |
| ⚪️ | [draw-session] Add slant | [Link](https://github.com/harfbuzz/harfbuzz/commit/aa5c7a381) | |
| ⚪️ | [font/draw] Slant drawings | [Link](https://github.com/harfbuzz/harfbuzz/commit/59067db9f) | |
| ⚪️ | [util] Add --font-slant | [Link](https://github.com/harfbuzz/harfbuzz/commit/4818b7ed7) | |
| ⚪️ | [font] Adjust synthetic-slant docs | [Link](https://github.com/harfbuzz/harfbuzz/commit/732c749ef) | |
| ⚪️ | [font] Update get_glyph_shape() doc | [Link](https://github.com/harfbuzz/harfbuzz/commit/bc6c3b840) | |
| ⚪️ | [draw] Flesh out docs a bit | [Link](https://github.com/harfbuzz/harfbuzz/commit/237623052) | |
| ⚪️ | [draw] Document more | [Link](https://github.com/harfbuzz/harfbuzz/commit/c56c13756) | |
| ⚪️ | [util/draw] Apply slant to non-user-fonts as well | [Link](https://github.com/harfbuzz/harfbuzz/commit/5c558586e) | |
| ⚪️ | [draw] Destroy callback data | [Link](https://github.com/harfbuzz/harfbuzz/commit/cdf1cb35d) | |
| ⚪️ | [meson] fix building with Cairo subproject | [Link](https://github.com/harfbuzz/harfbuzz/commit/cf2882133) | |
| ⚪️ | [doc] Message draw documentation a bit | [Link](https://github.com/harfbuzz/harfbuzz/commit/8e892bdb5) | |
| ⚪️ | [meson] Put back Experimental-API infrastructure | [Link](https://github.com/harfbuzz/harfbuzz/commit/8f519d55a) | |
| ⚪️ | [doc] Document HB_DRAW_STATE_DEFAULT | [Link](https://github.com/harfbuzz/harfbuzz/commit/7,25E+08) | |
| ⚪️ | [doc] Link to respective draw callback functions | [Link](https://github.com/harfbuzz/harfbuzz/commit/628847b5c) | |
| ⚪️ | [meson] Update cairo subproject | [Link](https://github.com/harfbuzz/harfbuzz/commit/74ebfc646) | |
| ⚪️ | [draw] Implement COLRv0 fonts | [Link](https://github.com/harfbuzz/harfbuzz/commit/6812f7ee1) | |
| ⚪️ | [draw] Fix conversion warnings | [Link](https://github.com/harfbuzz/harfbuzz/commit/18b8a1c34) | |
| ⚪️ | [util/draw] Use hb-draw in hb-view only if HB_DRAW=1 | [Link](https://github.com/harfbuzz/harfbuzz/commit/6a3dec357) | |
| ⚪️ | [util/draw] Explicitly chain from render_color_glyph to render_glyph | [Link](https://github.com/harfbuzz/harfbuzz/commit/22f2c78c2) | |
| ⚪️ | [util/draw] If HB_DRAW is not set | [Link](https://github.com/harfbuzz/harfbuzz/commit/9cc9ffe35) | |
| ⚪️ | [util] Default font-funcs to 'ot' instead of 'ft' | [Link](https://github.com/harfbuzz/harfbuzz/commit/640b6ffdd) | |
| ⚪️ | [draw] Add test for hb_draw_move_to() etc | [Link](https://github.com/harfbuzz/harfbuzz/commit/052fd2d8b) | |
| ⚪️ | [draw] Add test for applying synthetic slant | [Link](https://github.com/harfbuzz/harfbuzz/commit/aca80a4a4) | |
| ⚪️ | [draw] Emit move_to immediately | [Link](https://github.com/harfbuzz/harfbuzz/commit/151f20581) | |
| ⚪️ | [draw] Another try at a stable draw moveto semantic | [Link](https://github.com/harfbuzz/harfbuzz/commit/57aa8c3b3) | |
| ⚪️ | [util] Implement --sub-font | [Link](https://github.com/harfbuzz/harfbuzz/commit/096121bad) | |
| ⚪️ | [draw] Test scaling subfont differently from parent | [Link](https://github.com/harfbuzz/harfbuzz/commit/0e357c504) | |
| ⚪️ | [draw/glyf] Don't skip empty contours of size 2 | [Link](https://github.com/harfbuzz/harfbuzz/commit/0858463ac) | |
| ⚪️ | [meson] Update cairo submodule | [Link](https://github.com/harfbuzz/harfbuzz/commit/2da6accda) | |
| ⚪️ | [draw] Fix some introspection warnings | [Link](https://github.com/harfbuzz/harfbuzz/commit/f942874fa) | |
| ⚪️ | [algs] Fix typo in hb_pair_t conversion operator | [Link](https://github.com/harfbuzz/harfbuzz/commit/94517850d) | |
| ⚪️ | [draw/glyf] Emit empty contours | [Link](https://github.com/harfbuzz/harfbuzz/commit/d4588204e) | |
| ⚪️ | [draw/test] Add test for freetype callback | [Link](https://github.com/harfbuzz/harfbuzz/commit/0429921c1) | |
| ⚪️ | [test/draw] Typo | [Link](https://github.com/harfbuzz/harfbuzz/commit/ae223764a) | |
| ⚪️ | [draw/test] Swap a freetype test case with a simpler one | [Link](https://github.com/harfbuzz/harfbuzz/commit/6b75a30a7) | |
| ⚪️ | [meson] Update Cairo subproject | [Link](https://github.com/harfbuzz/harfbuzz/commit/c8b6036cf) | |
| ⚪️ | Remove return of void | [Link](https://github.com/harfbuzz/harfbuzz/commit/93962977b) | |
| ⚪️ | [ot-face] Load num-glyphs from \`loca\` table before \`maxp\` | [Link](https://github.com/harfbuzz/harfbuzz/commit/ed6d287d1) | |
| ⚪️ | [hmtx] Internal rename num_metrics to num_bearings | [Link](https://github.com/harfbuzz/harfbuzz/commit/622cbc485) | |
| ⚪️ | [hmtx] Rename internal num_advances to num_long_metrics | [Link](https://github.com/harfbuzz/harfbuzz/commit/be4ddcc30) | |
| ⚪️ | [hmtx] Document | [Link](https://github.com/harfbuzz/harfbuzz/commit/431c948ed) | |
| ⚪️ | [test] Add test for current hmtx logic | [Link](https://github.com/harfbuzz/harfbuzz/commit/379e526aa) | |
| ⚪️ | [hmtx] Implement [boring-expansion] >64k expansion | [Link](https://github.com/harfbuzz/harfbuzz/commit/8b7ccc41c) | |
| ⚪️ | Fix build | [Link](https://github.com/harfbuzz/harfbuzz/commit/531c27d19) | |
| ⚪️ | [test/api] Fix leaks | [Link](https://github.com/harfbuzz/harfbuzz/commit/197ed8f59) | |
| ⚪️ | [ci] Rename configs-ci to configs-build | [Link](https://github.com/harfbuzz/harfbuzz/commit/d12c51e6e) | |
| ⚪️ | [test/shape] Internal rename | [Link](https://github.com/harfbuzz/harfbuzz/commit/1bf588e28) | |
| ⚪️ | [config] Add HB_NO_BORING_EXPANSION | [Link](https://github.com/harfbuzz/harfbuzz/commit/67eb9acf7) | |
| ⚪️ | [machinery] Add "core table" machinery | [Link](https://github.com/harfbuzz/harfbuzz/commit/2a430790a) | |
| ⚪️ | [ot-face] Use core tables | [Link](https://github.com/harfbuzz/harfbuzz/commit/c8fd8c133) | |
| | [face] Use max numGlyphs of maxp and loca | [Link](https://github.com/harfbuzz/harfbuzz/commit/f567b5561) | |
| ⚪️ | Merge pull request #3411 from harfbuzz/draw | [Link](https://github.com/harfbuzz/harfbuzz/commit/a396543ae) | |
| ⚪️ | Improve docs for hb_ot_layout_get_ligature_carets | [Link](https://github.com/harfbuzz/harfbuzz/commit/9909e3326) | |
| ⚪️ | [autotools] Fix make distcheck | [Link](https://github.com/harfbuzz/harfbuzz/commit/cfa8cd7fb) | |
| ⚪️ | [ot-layout] Add +hb_ot_layout_get_horizontal_baseline_tag_for_script() | [Link](https://github.com/harfbuzz/harfbuzz/commit/98079109e) | |
| ⚪️ | Merge pull request #3410 from harfbuzz/boring-expansion | [Link](https://github.com/harfbuzz/harfbuzz/commit/d2998faad) | |
| ⚪️ | [ot-layout] Remove commented-out prototypes | [Link](https://github.com/harfbuzz/harfbuzz/commit/5de67c896) | |
| ⚪️ | [ot-layout] Synthesize missing baselines | [Link](https://github.com/harfbuzz/harfbuzz/commit/f81578fd8) | |
| ⚪️ | [ot-layout] Add central baselines | [Link](https://github.com/harfbuzz/harfbuzz/commit/95bb2ff71) | |
| ⚪️ | meson: Cleanup finding FreeType on Visual Studio | [Link](https://github.com/harfbuzz/harfbuzz/commit/561e8ba88) | |
| ⚪️ | meson: Clean up finding ICU-UC on Visual Studio | [Link](https://github.com/harfbuzz/harfbuzz/commit/f0573d846) | |
| ⚪️ | freetype2.wrap: Provide fallback for CMake dep as well | [Link](https://github.com/harfbuzz/harfbuzz/commit/d24ac4aac) | |
| ⚪️ | BUILD.md: Mention that installing CMake is recommended for MSVC | [Link](https://github.com/harfbuzz/harfbuzz/commit/e6aa4b7d0) | |
| ⚪️ | Merge pull request #3449 from fanc999/msvc-meson-use-cmake | [Link](https://github.com/harfbuzz/harfbuzz/commit/da801cdee) | |
| ⚪️ | Revert "hb-algs.hh: Fix build on Visual Studio 2015" | [Link](https://github.com/harfbuzz/harfbuzz/commit/8e900f2cd) | |
| ⚪️ | Merge pull request #3437 from matthiasclasen/synthesize-missing-baselines | [Link](https://github.com/harfbuzz/harfbuzz/commit/f8e9e315b) | |
| ⚪️ | [ot-metrics] Synthesize missing metrics | [Link](https://github.com/harfbuzz/harfbuzz/commit/f6efe34f5) | |
| ⚪️ | [subset] document return values. | [Link](https://github.com/harfbuzz/harfbuzz/commit/fc1548cf7) | |
| ⚪️ | [util] Rename template typenames to avoid clashing with actual types | [Link](https://github.com/harfbuzz/harfbuzz/commit/c0b2f50c0) | |
| 🟢 | [buffer] Add HB_BUFFER_FLAG_PRODUCE_UNSAFE_TO_CONCAT | [Link](https://github.com/harfbuzz/harfbuzz/commit/56f11ec93) | |
| ⚪️ | [hb-style] Fix synthetic slant values | [Link](https://github.com/harfbuzz/harfbuzz/commit/e76061a73) | |
| ⚪️ | [hb-style] Fix the sign of slant ratios | [Link](https://github.com/harfbuzz/harfbuzz/commit/16b232be0) | |
| ⚪️ | [style] Move the negation into the constant | [Link](https://github.com/harfbuzz/harfbuzz/commit/651c280d0) | |
| ⚪️ | Add a missing file | [Link](https://github.com/harfbuzz/harfbuzz/commit/d4cb07728) | |
| ⚪️ | [meson] handle multiple element ICU DEFS | [Link](https://github.com/harfbuzz/harfbuzz/commit/256dcde14) | |
| ⚪️ | Merge pull request #3459 from jameshilliard/icu-defs-mutliarg | [Link](https://github.com/harfbuzz/harfbuzz/commit/78f3d7f0a) | |
| ⚪️ | Merge pull request #3429 from harfbuzz/external_plan | [Link](https://github.com/harfbuzz/harfbuzz/commit/222301bfa) | |
| ⚪️ | Merge pull request #3423 from harfbuzz/revert-ci-msvc | [Link](https://github.com/harfbuzz/harfbuzz/commit/924dd71de) | |
| ⚪️ | [doc] Various fixes to newly added documentation | [Link](https://github.com/harfbuzz/harfbuzz/commit/1b5a2e080) | |
| ⚪️ | [subset] Rename codepoint -> unicode in subset plan api | [Link](https://github.com/harfbuzz/harfbuzz/commit/f6071c16b) | |
| ⚪️ | [doc] Typo | [Link](https://github.com/harfbuzz/harfbuzz/commit/6e466256e) | |
| ⚪️ | 4.0.0 | [Link](https://github.com/harfbuzz/harfbuzz/commit/8d1b000a3) | |
| ⚪️ | Minor [ci skip] | [Link](https://github.com/harfbuzz/harfbuzz/commit/756395270) | |
| ⚪️ | Fixed various misc. typos | [Link](https://github.com/harfbuzz/harfbuzz/commit/cf3a0f7ab) | |
| ⚪️ | Merge pull request #3464 from luzpaz/typos | [Link](https://github.com/harfbuzz/harfbuzz/commit/430246648) | |
| 🟢 | [aat] Update OT to AAT mappings for hist and vrtr | [Link](https://github.com/harfbuzz/harfbuzz/commit/05b3bdb0b) | |
| 🟢 | [USE] Restore the category WJ | [Link](https://github.com/harfbuzz/harfbuzz/commit/5b0a59812) | |
| 🟢 | [USE] Allow any non-numeric tail in symbol cluster | [Link](https://github.com/harfbuzz/harfbuzz/commit/6e059a46b) | |
| 🟢 | [USE] Simplify \`not_ccs_default_ignorable\` | [Link](https://github.com/harfbuzz/harfbuzz/commit/8,54E+10) | |
| 🟢 | [USE] Remove obsolete symbol/punctuation overrides | [Link](https://github.com/harfbuzz/harfbuzz/commit/e497a8f14) | |
| 🟢 | [USE] Treat all gc=Cn as independent clusters | [Link](https://github.com/harfbuzz/harfbuzz/commit/c33468d48) | |
| 🟢 | [USE] Remove obsolete overrides | [Link](https://github.com/harfbuzz/harfbuzz/commit/13bb46cfd) | |
| 🟢 | Update IANA Language Subtag Registry to 2022-03-02 | [Link](https://github.com/harfbuzz/harfbuzz/commit/e5707a440) | |
| ⚪️ | [layout] Fix handling of baseline variations | [Link](https://github.com/harfbuzz/harfbuzz/commit/e7ab42b24) | |
| ⚪️ | [repacker] expose hb_subset_repack() API | [Link](https://github.com/harfbuzz/harfbuzz/commit/a35757c6b) | |
| ⚪️ | [doc] Add experimental repacker API to private section | [Link](https://github.com/harfbuzz/harfbuzz/commit/a34eea301) | |
| ⚪️ | 4.0.1 | [Link](https://github.com/harfbuzz/harfbuzz/commit/1f79ba940) |

### CODE REVIEW

**Comment by LaurenzV** [comment]
Most changes were irrelevant, because a lot of them are for the `draw` API which don't matter for us (right?).

There were a couple of changes which I think belong to `ttf-parser`, but I still marked them as orange so you can take a quick look because I want to err on the side of caution, so this time there are more commits marked as orange, but a lot of them depend on each other.

P.S: I tried to port to 4.1 as well so that we're straight at the `reorg` commits,  but the commit directly after introduces changes to the ragel machine which makes it look different and it doesn't compile anymore, and I don't know how it works... So I think someone who knows how it works will have to take a stab at that one.

**Comment by RazrFalcon** [comment]
>Most changes were irrelevant, because a lot of them are for the draw API which don't matter for us (right?).

Yep. We have ttf-parser for that.

>commit directly after introduces changes to the ragel machine which makes it look different and it doesn't compile anymore

You mean `rl` files were changed and `ragel` cannot produce Rust code anymore?

>[ot-math] Add hb_ot_math_get_glyph_kernings

Not sure about now, but when I was originally porting harfbuzz, the MATH tables wasn't used during shaping.
And the only reason it is present in ttf-parser is because someone needed it. But rustybuzz doesn't use it.

Once again, harfbuzz isn't just a shaper, it's a collection of things. rustybuzz just a shaper.

>[font] Add em_scaleff() that returns float

Irrelevant. We do not support font scaling. For better or worse. 
There are some edge cases and quirks, but in most cases it can be done by the caller it whatever way it wants. 

>[draw-session] Add slant

Irrelevant. 

>[ot-face] Load num-glyphs from `loca` table before `maxp`
>[face] Use max numGlyphs of maxp and loca

Irrelevant. It's a ttf-parser problem to handle malformed fonts. 

>[hmtx] Internal rename num_metrics to num_bearings
>[hmtx] Rename internal num_advances to num_long_metrics

Irrelevant. TrueType parsing is out of the scope unless tests are failing.

>[hmtx] Implement [boring-expansion] >64k expansion

There are no plans to support TrueType extensions.

>[ot-layout] Add +hb_ot_layout_get_horizontal_baseline_tag_for_script()
>[ot-layout] Synthesize missing baselines
>[ot-layout] Add central baselines
>[ot-metrics] Synthesize missing metrics

Irrelevant. rustybuzz only does shaping. It has no font info getters.

**Comment by LaurenzV** [comment]
> You mean rl files were changed and ragel cannot produce Rust code anymore?

I can still produce Rust code. But the Rust code now looks a lot different and just changing "0" to "p0" doesn't fix it anymore, there's more broken stuff in there. If you want I can make a separate branch with just that one commit to demonstrate.

**Comment by LaurenzV** [comment]
> There are no plans to support TrueType extensions.

So all of the >64k expansion commits can probably be ignored for the future?

**Comment by RazrFalcon** [comment]
Then the only way is to send a bugreport to ragel, but it's kinda dead, so what's the point... In the worst case scenario we could fallback to manual C to Rust code conversion, as it was done originally.

>Yeah, I know. :p But sometimes I'm still a bit unsure so I'd rather just ask instead of straight up ignoring it, I hope you don't mind. If you do then I can also try to trust my "intuition" more in the future.

You can still ask if unsure, I don't mind. Again, all I care about it that tests are passing.

>So all of the >64k expansion commits can probably be ignored for the future?

Yes, we're not interested in this. Those changes are not part of the TrueType spec.

**Comment by LaurenzV** [comment]
I guess for 4.0.1 this should be complete then.

**Comment by LaurenzV** [comment]
Okay I made some more manual changes to the machine and it seems like it works, including the new test cases that were added. So maybe I will try all of 4.1 tomorrow. Don't seem to be too many commits anyway, but no promises.

But we can still merge 4.0.1 as is, I think.

**Comment by RazrFalcon** [comment]
Thanks!

**Pull request merged**
