### PR TITLE
Add a codegen check to the CI

### PR DESCRIPTION
**Pull request by notgull**
This ensures that all generated code is up to date.

### CODE REVIEW

**Comment by RazrFalcon** [comment]
Sorry, but I don't think this is a good idea. I don't want to have a complicated CI. 
Especially building C from sources. A minor GCC/autotools update and good luck figuring out what is wrong. Nah.

Also, you cannot really forget to update those files, because tests would be failing.

**Comment by notgull** [comment]
Okay, I'll reopen it once there is progress on https://github.com/taiki-e/install-action/issues/199

**Comment by RazrFalcon** [comment]
No, I don't think we need _any_ changes to CI at all. It's fine.

**Comment by notgull** [comment]
Are you sure? I help maintain [`x11rb`](https://github.com/psychon/x11rb), which uses a lot of pre-generated code. Having a check like this is invaluable for preventing the usual mistake of "forgot to run the build scripts again".

**Comment by RazrFalcon** [comment]
>forgot to run the build scripts again

It would not happen, because tests would fail. We have almost 2000 tests. The chance you forget something is tiny.
Again, simplicity is king. The current CI is good enough.

**Pull request closed without merging**
