### PR TITLE
Sync with 3.0.0.

### PR DESCRIPTION
**Pull request by LaurenzV**
My first attempt. let's see how it goes.

Legend:
🟢: Port of commit succeeded
⚪️: Commit is not relevant
🟡: I have uncertainties about that commit
🔴: Port of commit is failing
⚫️: Commit has not been ported yet.

Table:
| Status | Commit message                                                                  | HB Link                                                       |
| ------ | ------------------------------------------------------------------------------- | ------------------------------------------------------------- |
| ⚪️     | Typo                                                                            | [Link](https://github.com/harfbuzz/harfbuzz/commit/48c9869bd) |
| ⚪️     | [ci] Use different executer for win64 jobs                                      | [Link](https://github.com/harfbuzz/harfbuzz/commit/e38b873ea) |
| ⚪️     | [docs] Fix subset documentation                                                 | [Link](https://github.com/harfbuzz/harfbuzz/commit/9b7af950b) |
| ⚪️     | [subset] Improve alignment of --help-all message                                | [Link](https://github.com/harfbuzz/harfbuzz/commit/838d67075) |
| ⚪️     | [subset] fox for (Chain)ContextFormat3: subset lookupRecord                     | [Link](https://github.com/harfbuzz/harfbuzz/commit/37379f8f7) |
| ⚪️     | [style] Fall back to GPOS 'size' feature for optical size in style API          | [Link](https://github.com/harfbuzz/harfbuzz/commit/a23ce2897) |
| ⚪️     | [style] Rename HB_STYLE_TAG_SLANT to HB_STYLE_TAG_SLANT_ANGLE                   | [Link](https://github.com/harfbuzz/harfbuzz/commit/201cbe3c6) |
| ⚪️     | [style] Add HB_STYLE_TAG_SLANT_RATIO                                            | [Link](https://github.com/harfbuzz/harfbuzz/commit/39c20d2b9) |
| ⚪️     | Fix build with -Dexperimental_api=true                                          | [Link](https://github.com/harfbuzz/harfbuzz/commit/34ff2d3ea) |
| ⚪️     | [style] Prepare for release                                                     | [Link](https://github.com/harfbuzz/harfbuzz/commit/4d9b7de0b) |
| ⚪️     | [style] Fix documentation                                                       | [Link](https://github.com/harfbuzz/harfbuzz/commit/eb4075a1e) |
| ⚪️     | [style] Try to fix MSVC build                                                   | [Link](https://github.com/harfbuzz/harfbuzz/commit/e275f0d7e) |
| ⚪️     | [style] Try harder to fix MSVC build                                            | [Link](https://github.com/harfbuzz/harfbuzz/commit/d748586a1) |
| ⚪️     | [style] Change private slant tag                                                | [Link](https://github.com/harfbuzz/harfbuzz/commit/c5cc23a9b) |
| ⚪️     | [style] Fix float conversion warning                                            | [Link](https://github.com/harfbuzz/harfbuzz/commit/ad4df20dd) |
| ⚪️     | Call atexit() via hb_atexit()                                                   | [Link](https://github.com/harfbuzz/harfbuzz/commit/ed1163208) |
| 🟢     | [ot-shape] Enabled two more features: 'Harf' and 'Buzz'                         | [Link](https://github.com/harfbuzz/harfbuzz/commit/5a1a6f1fe) |
| ⚪️     | [style] Fix another float conversion warning                                    | [Link](https://github.com/harfbuzz/harfbuzz/commit/9c2704515) |
| ⚪️     | Add fallback atexit implementation using template descrutors                    | [Link](https://github.com/harfbuzz/harfbuzz/commit/bda3238c8) |
| ⚪️     | [util/shape-consumer] Simplify font tracking                                    | [Link](https://github.com/harfbuzz/harfbuzz/commit/da285d511) |
| ⚪️     | [util] Fix leak of an hb_font_t                                                 | [Link](https://github.com/harfbuzz/harfbuzz/commit/cd77846bd) |
| 🟢     | [Unicode 14] Add new \`hb_script_t\` values                                     | [Link](https://github.com/harfbuzz/harfbuzz/commit/67f1aa4d2) |
| ⚪️     | [Unicode 14] Update the UCD table                                               | [Link](https://github.com/harfbuzz/harfbuzz/commit/26e1498e7) |
| 🟢     | [Unicode 14] Update the script direction list                                   | [Link](https://github.com/harfbuzz/harfbuzz/commit/7b05eec05) |
| 🟢     | [Unicode 14] Update the Arabic table                                            | [Link](https://github.com/harfbuzz/harfbuzz/commit/18a46eeaf) |
| 🟢     | [Unicode 14] Update the Indic table                                             | [Link](https://github.com/harfbuzz/harfbuzz/commit/11d5334d8) |
| 🟢     | [Unicode 14] Update the vowel constraint table                                  | [Link](https://github.com/harfbuzz/harfbuzz/commit/ec5688f50) |
| ⚪️     | [Unicode 14] Update the emoji table                                             | [Link](https://github.com/harfbuzz/harfbuzz/commit/35ac0de42) |
| 🟢     | [Unicode 14] Update the USE table                                               | [Link](https://github.com/harfbuzz/harfbuzz/commit/20736d9bb) |
| 🟢     | [Unicode 14] Send all the new scripts to USE                                    | [Link](https://github.com/harfbuzz/harfbuzz/commit/2c3e4b279) |
| ⚪️     | [Unicode 14] Add tests                                                          | [Link](https://github.com/harfbuzz/harfbuzz/commit/a0101a31b) |
| 🟢     | [Unicode 14] Update the Arabic joining script list                              | [Link](https://github.com/harfbuzz/harfbuzz/commit/f1493357f) |
| ⚪️     | Merge pull request #3206 from harfbuzz/unicode-14                               | [Link](https://github.com/harfbuzz/harfbuzz/commit/175f24a45) |
| ⚪️     | [meson] Require ragel 6.10                                                      | [Link](https://github.com/harfbuzz/harfbuzz/commit/7e9ac8fea) |
| ⚪️     | [ragel] Regenerate state machine files with 6.10                                | [Link](https://github.com/harfbuzz/harfbuzz/commit/5898a9618) |
| ⚪️     | [meson] Add ragel subproject                                                    | [Link](https://github.com/harfbuzz/harfbuzz/commit/22cbd038d) |
| 🟢     | [USE] Send Khitan Small Script and Yezidi to USE                                | [Link](https://github.com/harfbuzz/harfbuzz/commit/470686e8)  |
| ⚪️     | [style] Change tag type to hb_style_tag_t                                       | [Link](https://github.com/harfbuzz/harfbuzz/commit/ae1453785) |
| ⚪️     | CMake: Detect pthread with module FindThread                                    | [Link](https://github.com/harfbuzz/harfbuzz/commit/19cd84b4e) |
| ⚪️     | [subset] In preperation for 3.0.0 release remove legacy subsetting api methods. | [Link](https://github.com/harfbuzz/harfbuzz/commit/d700646c3) |
| ⚪️     | [subset] restore hb_subset_input_unicode/glyph_set () to documentation.         | [Link](https://github.com/harfbuzz/harfbuzz/commit/f4649f389) |
| ⚪️     | Merge pull request #3210 from NikitaFeodonit/main                               | [Link](https://github.com/harfbuzz/harfbuzz/commit/60a38d798) |
| ⚪️     | [meson] Add ragel_subproject option                                             | [Link](https://github.com/harfbuzz/harfbuzz/commit/a59e7ec99) |
| ⚪️     | [ci] Build ragel on the Linux CI job                                            | [Link](https://github.com/harfbuzz/harfbuzz/commit/835fc1376) |
| ⚪️     | [ci] Ragel subproject requires meson 0.55.0                                     | [Link](https://github.com/harfbuzz/harfbuzz/commit/f1b20b5a1) |
| ⚪️     | [ci] meson 0.55.0 didn‚Äôt work for harfbuzz                                    | [Link](https://github.com/harfbuzz/harfbuzz/commit/671f1d149) |
| ⚪️     | Centralize math include                                                         | [Link](https://github.com/harfbuzz/harfbuzz/commit/e0d5fe740) |
| ⚪️     | 3.0.0                                                                           | [Link](https://github.com/harfbuzz/harfbuzz/commit/9c387e20d) |

### CODE REVIEW

**Comment by LaurenzV** [comment]
I tried updating the indic tables to 14.0

This added the following entry:
`use MatraCategory::TopAndBottomAndLeft as IMC_TBL;`

Now I need to update the following:

```rs
let c2 = match c2 {
        MatraCategory::NotApplicable => position::END,
        MatraCategory::Left => position::PRE_C,
        MatraCategory::Top => position::ABOVE_C,
        MatraCategory::Bottom => position::BELOW_C,
        MatraCategory::Right => position::POST_C,
        MatraCategory::BottomAndLeft => position::POST_C,
        MatraCategory::BottomAndRight => position::POST_C,
        MatraCategory::LeftAndRight => position::POST_C,
        MatraCategory::TopAndBottom => position::BELOW_C,
        MatraCategory::TopAndBottomAndRight => position::POST_C,
        MatraCategory::TopAndLeft => position::ABOVE_C,
        MatraCategory::TopAndLeftAndRight => position::POST_C,
        MatraCategory::TopAndRight => position::POST_C,
        MatraCategory::Overstruck => position::AFTER_MAIN,
        MatraCategory::VisualOrderLeft => position::PRE_M,
    };
```

Where/how can I read up on that so I know what to add here? 😅

**Comment by LaurenzV** [comment]
So as far as I can tell arabic tables and ucd tables are all covered by `gen-universal-table.py`? So for https://github.com/harfbuzz/harfbuzz/commit/18a46eeaf and https://github.com/harfbuzz/harfbuzz/commit/26e1498e7 it should be fine to just update that script to 14.0?

**Comment by LaurenzV** [comment]
And it seems like we have `gen-unicode-is-emoji-ext-pict.py` for emojis but no corresponding `.rs` file? How do I deal with that?

**Comment by RazrFalcon** [comment]
Wow, you have put a lot of effort into it. Much appreciated! 

>[style] Fall back to GPOS 'size' feature for optical size in style API

Yes, we don't have such API.

>[util/shape-consumer] Simplify font tracking

Yes, unrelated.

>[Unicode 14] Add tests

Yes, we don't have those.

>[meson] Require ragel 6.10

Yes, we use master branch already.

>So as far as I can tell arabic tables and ucd tables are all covered by gen-universal-table.py?

Afair, `hb-ot-shape-complex-arabic-table.hh` was ported by hand. At least there are no script for it and the file doesn't start with the `this file was generated` comment.
So you have to update it manually (which is very easy). Or port harfbuzz's script if you feel like it (harder).

As for `hb-ucd-table.hh`, we don't have it at all. We either use 3rd-party dependencies or our own scripts. Therefore updating to `14.0.0` in Python scripts + updating `unicode-*` crates should be enough.

**Comment by RazrFalcon** [comment]
We also have `src/unicode.rs:check_unicode_version` tests, in case you haven't so those. They all should be 14.0 now, I guess.

**Comment by LaurenzV** [comment]
Ah, I guess we need to update the dependencies too, then.

**Comment by LaurenzV** [comment]
Should I submit PR to those (unicode-cc and unicode-bidi)? Or is it faster if you just do it when you have time?

**Comment by LaurenzV** [comment]
```rs
#[derive(Clone, Copy, PartialEq, Debug)]
pub enum JoiningType {
    U = 0,
    L = 1,
    R = 2,
    D = 3,
    // We don't have C, like harfbuzz, because Rust doesn't allow duplicated enum variants.
    GroupAlaph = 4,
    GroupDalathRish = 5,
    T = 7,
    X = 8, // means: use general-category to choose between U or T.
}
```

Why would adding C here make it duplicated?

**Comment by RazrFalcon** [comment]
I will update my unicode crates soon.

>Why would adding C here make it duplicated?

Because Rust doesn't allow enums to have duplicate values.

**Comment by LaurenzV** [comment]
Right, so I always need to use D instead of C.

**Comment by RazrFalcon** [comment]
Yep.

**Comment by RazrFalcon** [comment]
Updated my `unicode-*` crates. Use version 0.2 for both.

**Comment by LaurenzV** [comment]
Okay, just the emoji commit is missing now: https://github.com/harfbuzz/harfbuzz/commit/35ac0de42

I'm unsure what to do with it though. They basically add this file: https://www.unicode.org/Public/emoji/latest/emoji-test.txt

But it seems that this file doesn't contain any information on extended pictographics. But it seems we only use the file to generate that one method. Does this mean we can ignore this file?

**Comment by RazrFalcon** [comment]
Yes, I think we can ignore that emoji change. It doesn't seems to affect us.
harfbuzz is not just a shaper, but rather a font processing toolkit. It has far more features that we do not implement in rustybuzz.

The rule of thumb: if tests are passing - we're fine.

**Comment by LaurenzV** [comment]
I guess porting itself is not as hard as I thought, just time-consuming. But I will probably change my mind once I encounter my first not-passing test and spend hours with the debugger. 😄

**Comment by RazrFalcon** [comment]
Pretty much.

**Comment by khaledhosny** [comment]
> Okay, just the emoji commit is missing now: [harfbuzz/harfbuzz@35ac0de42](https://github.com/harfbuzz/harfbuzz/commit/35ac0de42)
> 
> I'm unsure what to do with it though. They basically add this file: https://www.unicode.org/Public/emoji/latest/emoji-test.txt
> 
> But it seems that this file doesn't contain any information on extended pictographics. But it seems we only use the file to generate that one method. Does this mean we can ignore this file?

This file is used to generate emoji test data (IIRC, to test that all emoji sequences are shaped as one cluster)

**Pull request merged**
